addons:
  postgresql: 9.6
before_script:
  - bundle exec rails db:setup
bundler_args: --jobs 4 --retry 3
cache: bundler
language: ruby
notifications:
  email: false
rvm:
  - 2.3.5
  - 2.4.2
script:
  - bundle exec rails bundle:audit
  - bundle exec license_finder --quiet
  - bundle exec rubocop
  - bundle exec rails test
sudo: false
