version: '3'

services:
   db:
     image: postgres:10
     volumes:
       - ./db_data:/var/lib/postgresql/data
     ports:
       - "3309:3306"
     restart: always
     env_file:
       - ./.env.local

   adminer:
    depends_on:
      - db
    links:
      - db
    image: adminer
    restart: always
    ports:
        - 8088:8080

   rails:
     depends_on:
       - db
     links:
       - db
     #image: renocollective/rails
     build: ../member-portal-docker
     volumes:
       - ./:/app
       - box:/box
     ports:
       - "3000:3000"
     restart: always
     env_file:
       - ./.env.local
     #command: bash -c 'bundle install --no-deployment && rails db:migrate && rails s'
     command: /start.sh

   box:
    image: busybox
    volumes:
      - box:/box

volumes:
    box:
