# Be sure to restart your server when you modify this file.

# defaults across all environments
defaults: &defaults
  database_url: "postgresql://<%= ENV.fetch("POSTGRES_USER") %>:<%= ENV.fetch("POSTGRES_PASSWORD") %>@<%= ENV.fetch("POSTGRES_HOST") %>/<%= ENV.fetch("POSTGRES_DB") %>"
  secret_key_base: "<%= ENV.fetch("SECRET_KEY_BASE") %>"

# apply shared configuration to environments
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
