# Be sure to restart your server when you modify this file.

# defaults across all environments
defaults: &defaults
  database_url: "<%= ENV.fetch("DATABASE_URL") %>"
  secret_key_base: "<%= ENV.fetch("SECRET_KEY_BASE") %>"
  algolia:
    api_key: <%= ENV.fetch("ALGOLIA_API_KEY") %>
    application_id: <%= ENV.fetch("ALGOLIA_APPLICATION_ID") %>

# apply shared configuration to environments
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
